# Project 1, Phase 2

Leon Alexander Akkad  
Dominik Baron  
Matthias Guzmits  
Pascal Pilz  
Aaron Zettler  

<div class="alert alert-warning">
    <h2>Auxiliary Percentage</h2>
    We were able to solve all <b>6/6</b> problems.
</div>

In [1]:
import numpy as np
import pandas as pd
from approx_gradient import approximate_gradient

## Newton method with Hessian modification

In [2]:
from NM_w_hessian_mod import function_1, function_2, eig_val_mod, add_id, no_mod, newtons_method_hessian_mod
from approx_gradient import approximate_gradient, approximate_hessian

start_points = {'function_1': np.array([[1.2, 1.2], [-1.2, 1], [0.2, 0.8]]),
                'function_2': np.array([[-0.2, 1.2], [3.8, 0.1], [1.9, 0.6]])}
functions = {'function_1': function_1(),
             'function_2': function_2()}


for mod_method in [eig_val_mod, no_mod]:
    print('='*80)
    print('='*80)
    print('='*80)
    print()
    if mod_method == eig_val_mod:
        print(f'Using Eigenvalue Modifiction.')
        print()
    else:
        print(f'Using no modifcation, i.e. normal Newton Method.')
        print()
    for grad_method in ['symbolic', 'numeric']:
        print('='*70)
        print('='*70)
        print()
        print(f'using {grad_method} method to get the gradient')
        print()
        for function in functions:
            f, grad_f, hess_f = functions[function]
            if grad_method == 'numeric':
                grad_f = lambda x: approximate_gradient(f, x)
                hess_f = lambda x: approximate_hessian(f, x)
            print('='*60)
            print()
            print(f'{function}: {f.__doc__}')
            print()
            for x_0 in start_points[function]:
                print('-'*50)
                print(f'starting point: {x_0}')
                print()
                x_fin, p_fin, a_fin, n_iter = newtons_method_hessian_mod(
                    x_0, f, grad_f, hess_f, stop_crit=1e-6, print_interval=False, hess_modifier=mod_method)
                result = x_fin[-1]
                print(f'iterations:   {n_iter}')
                print(f'norm of grad: {np.linalg.norm(grad_f(result))}')
                print(f'endpoint:     {result}')
                print()


Using Eigenvalue Modifiction.


using symbolic method to get the gradient


function_1: 100*(x[1] - x[0]**2)**2 + (1 - x[0])**2

--------------------------------------------------
starting point: [1.2 1.2]

[[1250. -480.]
 [-480.  200.]]
[-115.6   48. ]
[[1146.18325698 -478.36734694]
 [-478.36734694  200.        ]]
[-0.3998062   0.00333195]
[[ 818.29312992 -400.26024856]
 [-400.26024856  200.        ]]
[-15.26302143   7.62589852]
[[ 802.92057877 -400.23007795]
 [-400.23007795  200.        ]]
[-1.15266675e-03  1.13783156e-06]
[[ 802.00013339 -400.00000026]
 [-400.00000026  200.        ]]
[-1.32340671e-04  6.61696811e-05]
iterations:   5
norm of grad: 1.1368683772161603e-13
endpoint:     [1. 1.]

--------------------------------------------------
starting point: [-1.2  1. ]

[[1330.  480.]
 [ 480.  200.]]
[215.6  88. ]
[[1107.2725666   470.11235955]
 [ 470.11235955  200.        ]]
[4.63781641 0.12220679]
[[1970.82670983 -305.24594847]
 [-305.24594847  200.        ]]
[-1146.45069037   75

LinAlgError: Singular matrix

## linear CG

In [ ]:
import funcs as fc
from linear_cg import linear_cg
from steepest_descent import steepest_descent

pd.options.display.max_colwidth = 1000

inputs = [
    (fc.l_f1_grad, np.array([5., -120., 630., -1120.00000001, 630.])),
    (fc.l_f2_grad, np.array([-8.00000052e+00, 5.04000025e+02, -7.56000030e+03, 4.62000015e+04, -1.38600004e+05, 2.16216005e+05,
                 -1.68168004e+05, 5.14800010e+04])),
    (fc.l_f3_grad, np.array([-1.28758021e+01, 1.82700490e+03, -6.35497518e+04, 9.48423728e+05,
                          -7.55539458e+06, 3.58352883e+07, -1.07176657e+08, 2.07239527e+08,
                          -2.58446725e+08, 2.00601048e+08, -8.81030636e+07, 1.67194346e+07])),
    (fc.l_f4_grad, np.array([-3.06198188e+01, 5.79631108e+03, -2.67656855e+05, 5.30590627e+06,
                          -5.62934738e+07, 3.56180768e+08, -1.41454296e+09, 3.54689896e+09,
                          -5.26881741e+09, 3.31570124e+09, 2.23492076e+09, -4.62144407e+09,
                          -4.79904240e+08, 5.96741325e+09, -4.19120773e+09, -4.68358103e+08,
                          1.17802999e+09, 4.13333400e+08, -7.15516924e+08, 1.98562765e+08])),
    (fc.l_f5_grad, np.array([-9.82482439e+00, 1.83726227e+03, -8.40808229e+04, 1.63655657e+06,
                          -1.67132563e+07, 9.84342322e+07, -3.42619774e+08, 6.54384034e+08,
                          -3.64246837e+08, -1.23608428e+09, 3.33110919e+09, -4.11395369e+09,
                          3.61640475e+09, -3.04010905e+09, 2.03383571e+09, -6.12820729e+08,
                          5.54105091e+08, -1.97634656e+09, 2.17304903e+09, 2.29862444e+08,
                          -1.61735957e+09, -5.59274698e+08, 1.42743422e+09, 9.15511460e+08,
                          -4.43132977e+08, -2.73444446e+09, 2.35525831e+09, 5.29596440e+08,
                          -1.25096008e+09, 3.87527105e+08]))
]
for grad_fn, sol in inputs:
    n_dims = sol.shape[0]
    
    x_k, r_k_norm, sol_diff_norm, iteration = linear_cg(grad_fn, np.zeros(shape=n_dims), sol, n_dims)
       
    df_dict = {
        '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
        '$$\Vert r_k\ \Vert$$': r_k_norm, 
        '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
        'iteration': iteration
    }
    
    df = pd.DataFrame(df_dict, index=[n_dims])
    display(df)

### Steepest Descent

In [ ]:
import funcs as fc
from linear_cg import linear_cg
from steepest_descent import steepest_descent

pd.options.display.max_colwidth = 1000

inputs = [
    (fc.l_f1_grad, np.array([5., -120., 630., -1120.00000001, 630.])),
    (fc.l_f2_grad, np.array([-8.00000052e+00, 5.04000025e+02, -7.56000030e+03, 4.62000015e+04, -1.38600004e+05, 2.16216005e+05,
                 -1.68168004e+05, 5.14800010e+04])),
    (fc.l_f3_grad, np.array([-1.28758021e+01, 1.82700490e+03, -6.35497518e+04, 9.48423728e+05,
                          -7.55539458e+06, 3.58352883e+07, -1.07176657e+08, 2.07239527e+08,
                          -2.58446725e+08, 2.00601048e+08, -8.81030636e+07, 1.67194346e+07])),
    (fc.l_f4_grad, np.array([-3.06198188e+01, 5.79631108e+03, -2.67656855e+05, 5.30590627e+06,
                          -5.62934738e+07, 3.56180768e+08, -1.41454296e+09, 3.54689896e+09,
                          -5.26881741e+09, 3.31570124e+09, 2.23492076e+09, -4.62144407e+09,
                          -4.79904240e+08, 5.96741325e+09, -4.19120773e+09, -4.68358103e+08,
                          1.17802999e+09, 4.13333400e+08, -7.15516924e+08, 1.98562765e+08])),
    (fc.l_f5_grad, np.array([-9.82482439e+00, 1.83726227e+03, -8.40808229e+04, 1.63655657e+06,
                          -1.67132563e+07, 9.84342322e+07, -3.42619774e+08, 6.54384034e+08,
                          -3.64246837e+08, -1.23608428e+09, 3.33110919e+09, -4.11395369e+09,
                          3.61640475e+09, -3.04010905e+09, 2.03383571e+09, -6.12820729e+08,
                          5.54105091e+08, -1.97634656e+09, 2.17304903e+09, 2.29862444e+08,
                          -1.61735957e+09, -5.59274698e+08, 1.42743422e+09, 9.15511460e+08,
                          -4.43132977e+08, -2.73444446e+09, 2.35525831e+09, 5.29596440e+08,
                          -1.25096008e+09, 3.87527105e+08]))
]

linear_cg_dfs = []
steepest_descent_dfs = []

for grad_fn, sol in inputs:
    n_dims = sol.shape[0]
    
    x_k, r_k_norm, sol_diff_norm, iteration = steepest_descent(
        grad_fn, 
        np.zeros(shape=n_dims), 
        sol, 
        n_dims,
        max_iter=int(1.5e6)
    )
       
    df_dict = {
        '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
        '$$\Vert r_k\ \Vert$$': r_k_norm, 
        '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
        'iteration': iteration
    }
    
    df = pd.DataFrame(df_dict, index=[n_dims])
    display(df)

TODO: explanation why no convergy

## Nonlinear CG

### Fletcher-Reevers

In [ ]:
from fr_cg import fr_cg
import funcs as fc

inputs_rosenbrock = [
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([1.2, 1.2]), np.array([1., 1.])),
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([-1.2, 1.]), np.array([1., 1.])),
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([0.2, 0.8]), np.array([1., 1.])),
]
rosenbrock_dicts = []

for fn, fn_grad_orig, x_0, x_star in inputs_rosenbrock:
    
    fn_grad_approx = lambda x: approximate_gradient(fn, x)
    
    for fn_grad, is_approx in [(fn_grad_orig, False), (fn_grad_approx, True)]:
        x_k, r_k_norm, sol_diff_norm, iteration = fr_cg(fn, fn_grad, x_0, x_star)
        rosenbrock_dicts.append({
            'approximation?': 'Actual Gradient' if not is_approx else 'Approx. Gradient',
            '$$x_0$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_0]) + r'\end{pmatrix}$$',
            '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
            '$$\Vert r_k\ \Vert$$': r_k_norm, 
            '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
            'iteration': iteration
        })

display(pd.DataFrame(rosenbrock_dicts))   
    

In [ ]:
from fr_cg import fr_cg
import funcs as fc

inputs_nl_f = [
    (fc.nl_f, fc.nl_f_grad, np.array([-0.2, 1.2]), np.array([0., 1.])),
    (fc.nl_f, fc.nl_f_grad, np.array([3.8, 0.1]), np.array([4., 0.])),
    (fc.nl_f, fc.nl_f_grad, np.array([1.9, 0.6]), np.array([0., 1.])),
]
nl_f_dicts = []

for fn, fn_grad_orig, x_0, x_star in inputs_nl_f:
    
    fn_grad_approx = lambda x: approximate_gradient(fn, x)
    
    for fn_grad, is_approx in [(fn_grad_orig, False), (fn_grad_approx, True)]:
        x_k, r_k_norm, sol_diff_norm, iteration = fr_cg(fn, fn_grad, x_0, x_star)
        nl_f_dicts.append({
            'approximation?': 'Actual Gradient' if not is_approx else 'Approx. Gradient',
            '$$x_0$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_0]) + r'\end{pmatrix}$$',
            '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
            '$$\Vert r_k\ \Vert$$': r_k_norm, 
            '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
            'iteration': iteration
        })

display(pd.DataFrame(nl_f_dicts))   
    

### Polak-Ribiere

In [ ]:
from pr_cg import pr_cg
import funcs as fc

inputs_rosenbrock = [
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([1.2, 1.2]), np.array([1., 1.])),
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([-1.2, 1.]), np.array([1., 1.])),
    (fc.rosenbrock, fc.rosenbrock_gradient, np.array([0.2, 0.8]), np.array([1., 1.])),
]
rosenbrock_dicts = []

for fn, fn_grad_orig, x_0, x_star in inputs_rosenbrock:
    
    fn_grad_approx = lambda x: approximate_gradient(fn, x)
    
    for fn_grad, is_approx in [(fn_grad_orig, False), (fn_grad_approx, True)]:
        x_k, r_k_norm, sol_diff_norm, iteration = pr_cg(fn, fn_grad, x_0, x_star)
        rosenbrock_dicts.append({
            'approximation?': 'Actual Gradient' if not is_approx else 'Approx. Gradient',
            '$$x_0$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_0]) + r'\end{pmatrix}$$',
            '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
            '$$\Vert r_k\ \Vert$$': r_k_norm, 
            '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
            'iteration': iteration
        })

display(pd.DataFrame(rosenbrock_dicts))   
    

In [ ]:
from pr_cg import pr_cg
import funcs as fc

inputs_nl_f = [
    (fc.nl_f, fc.nl_f_grad, np.array([-0.2, 1.2]), np.array([0., 1.])),
    (fc.nl_f, fc.nl_f_grad, np.array([3.8, 0.1]), np.array([4., 0.])),
    (fc.nl_f, fc.nl_f_grad, np.array([1.9, 0.6]), np.array([0., 1.])),
]
nl_f_dicts = []

for fn, fn_grad_orig, x_0, x_star in inputs_nl_f:
    
    fn_grad_approx = lambda x: approximate_gradient(fn, x)
    
    for fn_grad, is_approx in [(fn_grad_orig, False), (fn_grad_approx, True)]:
        x_k, r_k_norm, sol_diff_norm, iteration = pr_cg(fn, fn_grad, x_0, x_star)
        nl_f_dicts.append({
            'approximation?': 'Actual Gradient' if not is_approx else 'Approx. Gradient',
            '$$x_0$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_0]) + r'\end{pmatrix}$$',
            '$$x_k$$': r'$$\begin{pmatrix}' + r' \\ '.join([str(round(d, 2)) for d in x_k]) + r'\end{pmatrix}$$', 
            '$$\Vert r_k\ \Vert$$': r_k_norm, 
            '$$\Vert x^* - x_k \Vert$$': sol_diff_norm, 
            'iteration': iteration
        })

display(pd.DataFrame(nl_f_dicts))   
    

## QN methods

In [2]:
import math
from qn.optimization import bfgs_method, sr1_method
from qn.problems import rosenbrock, rosenbrock_grad, rosenbrock_starting_points, rosenbrock_solutions
from qn.problems import function_2, function_2_grad, function_2_starting_points, function_2_solutions

In [3]:
def perform_QN(method, f, grad_orig, starting_points, sol_points, max_iter=100, epsilon=1e-6):
    for i, sp in enumerate(starting_points):
        print(f"Solving Problem-{i+1}, Starting Point: {sp}")
        x0 = np.array(sp)
        
        grad_approx = lambda x: approximate_gradient(f, x)
        
        for grad, is_approx in [(grad_orig, False), (grad_approx, True)]:
            x_opt, gnorm, num_iters = method(f, grad, x0, max_iter, epsilon)

            print(f"Optimal solution - {'with' if is_approx else 'without'} gradient approximation:")
            print(f"x = {x_opt}")
            print(f"norm of grad = {gnorm}")
            print(f"distance = {math.dist(x_opt, sol_points[i])}")
            print(f"Number of iterations: {num_iters}\n")

In [4]:
print("<Quasi Newton Method for the Rosenbrock function>")
print("BFGS"+"-"*50)
perform_QN(bfgs_method, rosenbrock, rosenbrock_grad, rosenbrock_starting_points, rosenbrock_solutions)
print("SR1-" + "-"*50)
perform_QN(sr1_method, rosenbrock, rosenbrock_grad, rosenbrock_starting_points, rosenbrock_solutions)

<Quasi Newton Method for the Rosenbrock function>
BFGS--------------------------------------------------
Solving Problem-1, Starting Point: (1.2, 1.2)
Optimal solution - without gradient approximation:
x = [1. 1.]
norm of grad = 3.9172139696307626e-08
distance = 1.9566929546729326e-09
Number of iterations: 11

Optimal solution - with gradient approximation:
x = [0.99969965 0.99939889]
norm of grad = 2.526352843790415e-08
distance = 0.0006719681680405487
Number of iterations: 11

Solving Problem-2, Starting Point: (-1.2, 1)
Optimal solution - without gradient approximation:
x = [1.00000001 1.00000001]
norm of grad = 1.0506595642943314e-07
distance = 1.4444376803793241e-08
Number of iterations: 34

Optimal solution - with gradient approximation:
x = [0.99969965 0.99939889]
norm of grad = 5.347668022084e-08
distance = 0.0006719678084843039
Number of iterations: 33

Solving Problem-3, Starting Point: (0.2, 0.8)
Optimal solution - without gradient approximation:
x = [1. 1.]
norm of grad = 1

In [5]:
print("<Quasi Newton Method for the second Function>")
print("BFGS"+"-"*50)
perform_QN(bfgs_method, function_2, function_2_grad, function_2_starting_points, function_2_solutions)
print("SR1-" + "-"*50)
perform_QN(sr1_method, function_2, function_2_grad, function_2_starting_points, function_2_solutions)

<Quasi Newton Method for the second Function>
BFGS--------------------------------------------------
Solving Problem-1, Starting Point: (-0.2, 1.2)
Optimal solution - without gradient approximation:
x = [ 4.000000e+00 -3.468578e-11]
norm of grad = 1.7076990231341392e-07
distance = 1.9989648552914663e-09
Number of iterations: 11

Optimal solution - with gradient approximation:
x = [ 4.00000150e+00 -5.00660451e-07]
norm of grad = 1.7580857129365691e-07
distance = 1.5811791399278446e-06
Number of iterations: 11

Solving Problem-2, Starting Point: (3.8, 0.1)
Optimal solution - without gradient approximation:
x = [4.00000000e+00 2.99090477e-13]
norm of grad = 1.5261767933646526e-09
distance = 4.3992493848322424e-11
Number of iterations: 8

Optimal solution - with gradient approximation:
x = [ 4.00000150e+00 -5.00624432e-07]
norm of grad = 1.617287441676314e-09
distance = 1.583179672288559e-06
Number of iterations: 8

Solving Problem-3, Starting Point: (1.9, 0.6)
Optimal solution - without g

## derivatives approximation

In [6]:
from approx_gradient import rosenbrock_function,\
                            rosenbrock_function_g,\
                            rosenbrock_function_h,\
                            function1, function1_g,\
                            function1_h,\
                            approximate_gradient, approximate_hessian

rosenbrock_function_sp = np.array([[1.2, 1.2], [-1.2, 1], [0.2, 0.8]])
function1_sp = np.array([[-0.2, 1.2], [3.8, 0.1], [1.9, 0.6]])

for i in range(3):
    real_ros_g = rosenbrock_function_g(rosenbrock_function_sp[i])
    appr_ros_g = approximate_gradient(rosenbrock_function, rosenbrock_function_sp[i])
    real_ros_h = rosenbrock_function_h(rosenbrock_function_sp[i])
    appr_ros_h = approximate_hessian(rosenbrock_function, rosenbrock_function_sp[i])
    print(f"Rosenbrock-Function at {rosenbrock_function_sp[i]}: {rosenbrock_function(rosenbrock_function_sp[i])}")
    print(f"Real Gradient of Rosenbrock-Function at {rosenbrock_function_sp[i]}: {real_ros_g}")
    print(f"Approximated Gradient of Rosenbrock-Function at {rosenbrock_function_sp[i]}: {appr_ros_g}")
    print(f"Norm: {np.linalg.norm(real_ros_g - appr_ros_g)}")
    print(f"Real Hessian of Rosenbrock-Function at {rosenbrock_function_sp[i]}:\n{real_ros_h}")
    print(f"Approximated Hessian of Rosenbrock-Function at {rosenbrock_function_sp[i]}:\n{appr_ros_h}")
    print(f"Norm: {np.linalg.norm(real_ros_h - appr_ros_h)}")
    print()
    
    real_f1_g = function1_g(function1_sp[i])
    appr_f1_g = approximate_gradient(function1, function1_sp[i])
    real_f1_h = function1_h(function1_sp[i])
    appr_f1_h = approximate_hessian(function1, function1_sp[i])
    print(f"Function1 at {function1_sp[i]}: {function1(function1_sp[i])}")
    print(f"Real Gradient of Function1 at {function1_sp[i]}: {real_f1_g}")
    print(f"Approximated Gradient of Function1 at {function1_sp[i]}: {appr_f1_g}")
    print(f"Norm: {np.linalg.norm(real_f1_g - appr_f1_g)}")
    print(f"Real Hessian of Function1 at {function1_sp[i]}:\n{real_f1_h}")
    print(f"Approximated Hessian of Function1 at {function1_sp[i]}:\n{appr_f1_h}")
    print(f"Norm: {np.linalg.norm(real_f1_h - appr_f1_h)}")
    print("="*80)


Rosenbrock-Function at [1.2 1.2]: 5.8
Real Gradient of Rosenbrock-Function at [1.2 1.2]: [115.6 -48. ]
Approximated Gradient of Rosenbrock-Function at [1.2 1.2]: [115.60062499 -47.9999    ]
Norm: 0.0006329373981467745
Real Hessian of Rosenbrock-Function at [1.2 1.2]:
[[1250. -480.]
 [-480.  200.]]
Approximated Hessian of Rosenbrock-Function at [1.2 1.2]:
[[1250.00054751 -480.00003972]
 [-480.00003972  200.00001655]]
Norm: 0.0005506367033515529

Function1 at [-0.2  1.2]: 8.73
Real Gradient of Function1 at [-0.2  1.2]: [-86.1  15.6]
Approximated Gradient of Function1 at [-0.2  1.2]: [-86.09978375  15.60001   ]
Norm: 0.00021648224992243072
Real Hessian of Function1 at [-0.2  1.2]:
[[ 432.5 -142. ]
 [-142.    20. ]]
Approximated Hessian of Function1 at [-0.2  1.2]:
[[ 432.50025783 -142.00018938]
 [-142.00018938   20.00000165]]
Norm: 0.0003717689734517968
Rosenbrock-Function at [-1.2  1. ]: 24.199999999999996
Real Gradient of Rosenbrock-Function at [-1.2  1. ]: [-215.6  -88. ]
Approximated 